DROP TABLE IF EXISTS MUSIC

DROP SEQUENCE IF EXISTS MUSIC_ID_SEQUENCE


CREATE SEQUENCE music_id_sequence START WITH 1 INCREMENT BY 1

CREATE TABLE MUSIC(
ID INT UNIQUE not null,
TITLERECORD VARCHAR(256) not null,
LYRICIST VARCHAR(256) not null,
ALBUM VARCHAR(100) not null,
CONSTRAINT MUSIC_PK PRIMARY KEY(id)
)